config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :cards
  devise_for :users
  get 'home/index'
  root to: 'home#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
	has_many :card_tags, dependent: :destroy
	has_many :tags, through: :card_tags
end

app/models/card_tag.rb
class CardTag < ActiveRecord::Base
	belongs_to :card	
	belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :card_tags, dependent: :destroy
	has_many :cards, through: :card_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController  
  before_action :authenticate_user!
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.where(user_id: current_user.id)
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @tag = Tag.new
    @tags = @card.tags
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        @card.update_attribute(:user_id, current_user.id)
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tag, only: [:show, :edit, :update, :destroy]  
  before_action :set_card, only: [:new, :create, :edit, :update, :destroy]
  before_action :all_tags, only: [:index, :create, :edit, :update, :destroy]  
  respond_to :html, :js

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create        
    @tag = Tag.create(tag_params)    
    CardTag.create(card_id: params[:card_id], tag_id: @tag.id)
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    @tag.update(tag_params)
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def all_tags
      @tags = @card.tags
    end

    def set_card
      @card = Card.find(params[:card_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/cards/_form.html.slim
= form_for @card do |f|
  - if @card.errors.any?
    #error_explanation
      h2 = "#{pluralize(@card.errors.count, "error")} prohibited this card from being saved:"
      ul
        - @card.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit

app/views/cards/edit.html.slim
h1 Editing card

== render 'form'

= link_to 'Show', @card
'|
= link_to 'Back', cards_path

app/views/cards/index.html.slim
h1 Listing cards

table
  thead
    tr
      th Name
      th Description
      th
      th
      th

  tbody
    - @cards.each do |card|
      tr
        td = card.name
        td = card.description
        td = link_to 'Show', card
        td = link_to 'Edit', edit_card_path(card)
        td = link_to 'Destroy', card, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Card', new_card_path

app/views/cards/new.html.slim
h1 New card

== render 'form'

= link_to 'Back', cards_path

app/views/cards/show.html.slim
p#notice = notice

= link_to "New Tag", new_tag_path(card_id: @card.id), remote: true

div id="tags"
  = render 'tags/tags'

div
  br
  div id="tag_form" style="display:none;"

p
  strong Name:
  = @card.name
p
  strong Description:
  = @card.description

= link_to 'Edit', edit_card_path(@card)
'|
= link_to 'Back', cards_path

app/views/home/index.html.slim
- if user_signed_in?  
  h2 Card search
- else  
  h1 Home#index
  p Find me in app/views/home/index.html.slim

app/views/layouts/_navigation.html.slim
nav
	- if user_signed_in?
	  li= link_to 'Edit account', edit_user_registration_path
	  li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
	- else
	  li= link_to 'Sign in', new_user_session_path
	  li= link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.erb
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Catalog2
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Catalog2
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = evil_icons_sprite
    = render 'layouts/navigation'
    = yield

app/views/tags/_form.html.slim
= form_for @tag, url: "/tags?card_id=#{@card.id}", remote: true do |f|
  - if @tag.errors.any?
    #error_explanation
      h2 = "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      ul
        - @tag.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/tags/_form_edit.html.slim
= form_for @tag, url: "/tags/#{@tag.id}?card_id=#{@card.id}", remote: true do |f|
  - if @tag.errors.any?
    #error_explanation
      h2 = "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      ul
        - @tag.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/tags/_tags.html.slim
- @tags.each do |tag|
  = " "   
  span.tag
    strong
      = " " + tag.name if tag.present?
    = " "
    = link_to "edit", "/tags/#{tag.id}/edit?card_id=#{@card.id}", remote: true
    = " "
    = link_to "x ", "/tags/#{tag.id}?card_id=#{@card.id}", method: :delete, data: {confirm: 'A you sure?'}, remote: true
    = " "  

app/views/tags/create.js.erb
$('#tags').html("<%= j (render 'tags') %>");
$('#tag_form').slideUp(200);

app/views/tags/destroy.js.erb
$('#tags').html("<%= j (render 'tags') %>");

app/views/tags/edit.html.slim
h1 Editing tag

== render 'form_edit'

= link_to 'Show', @tag
'|
= link_to 'Back', tags_path

app/views/tags/edit.js.erb
$('#tag_form').html("<%= j (render 'form_edit') %>");
$('#tag_form').slideDown(200);

app/views/tags/index.html.slim
h1 Listing tags

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @tags.each do |tag|
      tr
        td = tag.name
        td = link_to 'Show', tag
        td = link_to 'Edit', edit_tag_path(tag)
        td = link_to 'Destroy', tag, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Tag', new_tag_path

app/views/tags/new.html.slim
h1 New tag

== render 'form'

= link_to 'Back', tags_path

app/views/tags/new.js.erb
$('#tag_form').html("<%= j (render 'form') %>");
$('#tag_form').slideDown(200);

app/views/tags/show.html.slim
p#notice = notice

p
  strong Name:
  = @tag.name

= link_to 'Edit', edit_tag_path(@tag)
'|
= link_to 'Back', tags_path

app/views/tags/update.js.erb
$('#tags').html("<%= j (render 'tags') %>");
$('#tag_form').slideUp(200);